<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2MZnk3l\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2MZnk3l/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2MZnk3l.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2MZnk3l\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2MZnk3l\App_KernelDevDebugContainer([
    'container.build_hash' => '2MZnk3l',
    'container.build_id' => 'c91c34b9',
    'container.build_time' => 1712089572,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2MZnk3l');
