<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVwF6xzq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVwF6xzq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVwF6xzq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVwF6xzq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVwF6xzq\App_KernelDevDebugContainer([
    'container.build_hash' => 'VwF6xzq',
    'container.build_id' => '4215a6e4',
    'container.build_time' => 1709828185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVwF6xzq');
