<?php

namespace Container2MZnk3l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduit2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iGUm1r8.App\Entity\Produit' shared service.
     *
     * @return \App\Entity\Produit
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iGUm1r8": it references class "App\\Entity\\Produit" but no such service exists.');
    }
}
