<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://example.com/projectservice"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    name="ProjectService"
    targetNamespace="http://example.com/projectservice">

    <message name="assignTeamRequest">
        <part name="teamId" type="xsd:int" />
        <part name="projectId" type="xsd:int" />
    </message>

    <message name="assignTeamResponse">
        <part name="message" type="xsd:string" />
    </message>

    <portType name="ProjectPortType">
        <operation name="assignTeamToProject">
            <input message="tns:assignTeamRequest" />
            <output message="tns:assignTeamResponse" />
        </operation>
    </portType>

    <binding name="ProjectPortBinding" type="tns:ProjectPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="assignTeamToProject">
            <soap:operation soapAction="assignTeamToProject" style="document"/>
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
        </operation>
    </binding>

    <service name="ProjectService">
        <port name="ProjectPort" 
            binding="tns:ProjectPortBinding">
            <soap:address location="http://localhost:3000/ProjectService" />
        </port>
    </service>
</definitions>