<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMVRBQYE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMVRBQYE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMVRBQYE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMVRBQYE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMVRBQYE\App_KernelDevDebugContainer([
    'container.build_hash' => 'MVRBQYE',
    'container.build_id' => 'cdd61af5',
    'container.build_time' => 1712084037,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMVRBQYE');
