<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9IxghAp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9IxghAp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9IxghAp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9IxghAp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9IxghAp\App_KernelDevDebugContainer([
    'container.build_hash' => '9IxghAp',
    'container.build_id' => 'c2223b49',
    'container.build_time' => 1729554034,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container9IxghAp');
