<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'soap_affecter_membre' => [[], ['_controller' => 'App\\Controller\\SoapController::soapServer'], [], [['text', '/soap/affecter-membre']], [], [], []],
    'affecter_membre' => [[], ['_controller' => 'App\\Controller\\SoapController::affecterMembre'], [], [['text', '/soap/affecter-membre']], [], [], []],
    'App\Controller\SoapController::soapServer' => [[], ['_controller' => 'App\\Controller\\SoapController::soapServer'], [], [['text', '/soap/affecter-membre']], [], [], []],
];
