server:
  port: 8012
spring:
  application:
    name: CourtierService
  datasource:
    driver-class-name: org.postgresql.Driver
    password: Kayto404
    url: jdbc:postgresql://localhost:5432/dbCourtier
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
